import { Inter } from "next/font/google";
import "./globals.css";
import "@fortawesome/fontawesome-free/css/all.min.css";

const inter = Inter({ subsets: ["latin"] });
import StoreProvider from "./StoreProvider";
import Navbar from "./components/navbar/Navbar";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full px-3 py-0">
          <Navbar />
        </div>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
